name: deploy

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'  
        bundler-cache: true

    - name: Install Mermaid CLI
      run: npm install -g @mermaid-js/mermaid-cli

    - name: Install dependencies
      run: |
        rm -rf vendor
        rm -rf $GEM_HOME/specifications/default/uri*
        bundle install

    - name: Setup deploy options
      id: setup
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        if [[ ${GITHUB_REF} = refs/pull/*/merge ]]; then
          echo "SRC_BRANCH=${GITHUB_HEAD_REF}" >> $GITHUB_OUTPUT
          echo "NO_PUSH=--no-push" >> $GITHUB_OUTPUT
        elif [[ ${GITHUB_REF} = refs/heads/* ]]; then
          echo "SRC_BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
        fi
        echo "DEPLOY_BRANCH=gh-pages" >> $GITHUB_OUTPUT

    - name: Deploy website
      run: |
        yes | bash bin/deploy --verbose ${{ steps.setup.outputs.NO_PUSH }} \
        --src ${{ steps.setup.outputs.SRC_BRANCH }} \
        --deploy ${{ steps.setup.outputs.DEPLOY_BRANCH }}
